// Sidebar gerada automaticamente a partir da estrutura de pastas.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};
module.exports = sidebars;
